/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorPrincipal;
import java.awt.event.ActionListener;

/**
 *
 * @author nanas
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal(ControladorPrincipal control) {
        initComponents();
        escuchar(control);
    }

 
    
    public void escuchar(ActionListener control){
      jlmAyuda.addActionListener(control);
      jmlSalir.addActionListener(control);
      jmlSesion.addActionListener(control);
      jmlAdminUsuarios.addActionListener(control);
      jmlAdminRecetas.addActionListener(control);
      jmlRecetas.addActionListener(control);
      jmlUsuarios.addActionListener(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jml = new javax.swing.JMenu();
        jlmAyuda = new javax.swing.JMenuItem();
        jmlSesion = new javax.swing.JMenuItem();
        jmlSalir = new javax.swing.JMenuItem();
        jmlAdministracion = new javax.swing.JMenu();
        jmlAdminUsuarios = new javax.swing.JMenuItem();
        jmlAdminRecetas = new javax.swing.JMenuItem();
        jmConsultar = new javax.swing.JMenu();
        jmlRecetas = new javax.swing.JMenuItem();
        jmlUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagen.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jml.setText("Opciones");

        jlmAyuda.setText("Ayuda");
        jml.add(jlmAyuda);

        jmlSesion.setText("Inicio Sesíon");
        jml.add(jmlSesion);

        jmlSalir.setText("Salir");
        jmlSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlSalirActionPerformed(evt);
            }
        });
        jml.add(jmlSalir);

        jMenuBar1.add(jml);

        jmlAdministracion.setText("Administracíon");

        jmlAdminUsuarios.setText("Administracíon Usuarios");
        jmlAdminUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlAdminUsuariosActionPerformed(evt);
            }
        });
        jmlAdministracion.add(jmlAdminUsuarios);

        jmlAdminRecetas.setText("Administraciín Recetas ");
        jmlAdminRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlAdminRecetasActionPerformed(evt);
            }
        });
        jmlAdministracion.add(jmlAdminRecetas);

        jMenuBar1.add(jmlAdministracion);

        jmConsultar.setText("Consultas");

        jmlRecetas.setText("Recetas");
        jmConsultar.add(jmlRecetas);

        jmlUsuarios.setText("Usuarios");
        jmlUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlUsuariosActionPerformed(evt);
            }
        });
        jmConsultar.add(jmlUsuarios);

        jMenuBar1.add(jmConsultar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmlSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlSalirActionPerformed

    private void jmlAdminRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlAdminRecetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlAdminRecetasActionPerformed

    private void jmlUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlUsuariosActionPerformed

    private void jmlAdminUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlAdminUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlAdminUsuariosActionPerformed

  
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jlmAyuda;
    private javax.swing.JMenu jmConsultar;
    private javax.swing.JMenu jml;
    private javax.swing.JMenuItem jmlAdminRecetas;
    private javax.swing.JMenuItem jmlAdminUsuarios;
    private javax.swing.JMenu jmlAdministracion;
    private javax.swing.JMenuItem jmlRecetas;
    private javax.swing.JMenuItem jmlSalir;
    private javax.swing.JMenuItem jmlSesion;
    private javax.swing.JMenuItem jmlUsuarios;
    // End of variables declaration//GEN-END:variables
}
